import { Router, type IRouter } from "express";
import healthRouter from "./health";
import marketsRouter from "./markets";
import holdingsRouter from "./holdings";
import cashRouter from "./cash";
import subscriptionRouter from "./subscription";
import legalRouter from "./legal";
import configRouter from "./config";
import referralRouter from "./referral";
import pushRouter from "./push";
import accountRouter from "./account";
import inflationRouter from "./inflation";
import goalsRouter from "./goals";
import recurringIncomeRouter from "./recurringIncome";
import dividendsRouter from "./dividends";
import portfolioRouter from "./portfolio";
import priceAlertsRouter from "./priceAlerts";
import stripeCheckoutRouter from "./stripeCheckout";
import chatRouter from "./chat";
import activityRouter from "./activity";
import ttsRouter from "./tts";
import competitionRouter from "./competition";
import adminRouter from "./admin";

const router: IRouter = Router();

router.use(healthRouter);
router.use(marketsRouter);
router.use(holdingsRouter);
router.use(cashRouter);
router.use(subscriptionRouter);
router.use(legalRouter);
router.use(configRouter);
router.use(referralRouter);
router.use(pushRouter);
router.use(accountRouter);
router.use(inflationRouter);
router.use(goalsRouter);
router.use(recurringIncomeRouter);
router.use(dividendsRouter);
router.use(portfolioRouter);
router.use(priceAlertsRouter);
router.use(stripeCheckoutRouter);
router.use(chatRouter);
router.use(activityRouter);
router.use(ttsRouter);
router.use(competitionRouter);
router.use(adminRouter);

export default router;
